---
- name: Create empty file on App Server 2
  hosts: stratos
  become: true

  tasks:
    - name: Create /tmp/file.txt
      ansible.builtin.file:
        path: /tmp/file.txt
        state: touch
        mode: '0644'
